#pragma once

typedef enum sparkboxerror_t : int32_t {
  SPK_OK = 0,

  // FatFs errors (mapped to negative values of 
  // usual fatfs error codes)
  FATFS_FR_INVALID_PARAMETER = -19,
  FATFS_FR_TOO_MANY_OPEN_FILES,
  FATFS_FR_NOT_ENOUGH_CORE,
  FATFS_FR_LOCKED,
  FATFS_FR_TIMEOUT,
  FATFS_FR_MKFS_ABORTED,
  FATFS_FR_NO_FILESYSTEM,
  FATFS_FR_NOT_ENABLED,
  FATFS_FR_INVALID_DRIVE,
  FATFS_FR_WRITE_PROTECTED,
  FATFS_FR_INVALID_OBJECT,
  FATFS_FR_EXIST,
  FATFS_FR_DENIED,
  FATFS_FR_INVALID_NAME,
  FATFS_FR_NO_PATH,
  FATFS_FR_NO_FILE,
  FATFS_FR_NOT_READY,
  FATFS_FR_INT_ERR,
  FATFS_FR_DISK_ERR,

  // Video errors
  VIDEO_TOO_MANY_LAYERS = -199,
  VIDEO_INVALID_SPRITE_FILE,
  VIDEO_SPRITE_HEADER_READ,

  // GPU errors
  GPU_COMMUNICATION_ERROR = -299,
  GPU_NOT_ENOUGH_MEMORY,

  // Audio errors
  AUDIO_TOO_MANY_FILES = -399,
  AUDIO_BANK_INVALID_ID,
  AUDIO_INVALID_CHANNEL,
  AUDIO_UNSUPPORTED_FILE,

  // Controller errors
  CONTROLLER_NOT_CONNECTED = -499,
  CONTROLLER_INVALID_DATA
};