#ifndef SPARKBOX_ERRORS_HPP_
#define SPARKBOX_ERRORS_HPP_

typedef enum SparkboxError : int {
	SPARK_OK = 0,
	INIT_ALLOC_FAILED,


	AUDIO_INIT_ALLOC_FAILED = 100,
	AUDIO_DRIVER_STRUCT_INVALID,
	AUDIO_NOT_INITIALIZED,
	AUDIO_STREAM_OUT_OF_RANGE,
	AUDIO_FILE_NOT_IMPORTED,
	AUDIO_FATFS_ERROR,
	AUDIO_NOT_A_DIRECTORY,
	AUDIO_FILE_ALREADY_IMPORTED,
	AUDIO_FILE_INSUFFICIENT_MEMORY,
	AUDIO_FILE_INVALID_HEADER,
	AUDIO_FILE_IMPORT_FAILED,
	AUDIO_DMA_TRANSFER_FAILED,

	VIDEO_INIT_ALLOC_FAILED = 200,
	VIDEO_DRIVER_STRUCT_INVALID,
	VIDEO_NOT_INITIALIZED,
} sparkboxError_t;

#endif // SPARKBOX_ERRORS_HPP_