M48
; DRILL file {KiCad (6.0.2)} date Thu Mar 17 20:21:47 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-17T20:21:47-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.7569Y-4.1634
X3.7569Y-4.3209
T2
X4.3957Y-4.1644
X6.1565Y-4.5118
X6.1614Y-3.2244
T0
M30
