set(CMAKE_CXX_COMPILER g++ CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER gcc CACHE STRING "" FORCE)
set(CMAKE_GENERATOR "MinGW Makefiles" CACHE STRING "" FORCE)

set(SPARKBOX_DEVICE "HOST" CACHE STRING "" FORCE)
set(FREERTOS_HEAP "4" CACHE STRING "" FORCE)